INSERT INTO feedback (user_name, channel, urgency, theme, value, sentiment, message) VALUES
  ('Avery K.', 'In-app', 'high', 'product', 'retention', 'negative', 'Export flow fails when I include custom fields and it blocks end-of-quarter reporting.'),
  ('Jordan L.', 'Email', 'medium', 'support', 'efficiency', 'neutral', 'Support response times improved, but escalation steps are still unclear.'),
  ('Priya S.', 'Chat', 'low', 'ux', 'adoption', 'positive', 'Love the new onboarding checklist. It helped my team finish setup in one day.'),
  ('Mateo R.', 'In-app', 'high', 'performance', 'revenue', 'negative', 'Dashboard load times spike during peak hours and delay our sales calls.'),
  ('Chen W.', 'Survey', 'medium', 'pricing', 'revenue', 'negative', 'The new pricing tiers feel too restrictive for mid-sized teams.'),
  ('Elena P.', 'Chat', 'low', 'product', 'adoption', 'positive', 'Bulk edit saved us a ton of time this week.'),
  ('Samira D.', 'Email', 'high', 'security', 'retention', 'negative', 'We need SSO audit logs to meet compliance before renewal.'),
  ('Noah J.', 'In-app', 'medium', 'ux', 'efficiency', 'neutral', 'Navigation is better but the search filters are still buried.'),
  ('Iris T.', 'Survey', 'low', 'support', 'retention', 'positive', 'Customer success training was thorough and helped my team hit our goals.'),
  ('Omar H.', 'Chat', 'high', 'product', 'revenue', 'negative', 'The analytics export is missing campaign attribution data.'),
  ('Lina M.', 'Email', 'medium', 'performance', 'retention', 'neutral', 'We notice occasional lag when switching between accounts.'),
  ('Victor G.', 'In-app', 'low', 'pricing', 'adoption', 'positive', 'Annual plan discount made it easier to commit early.'),
  ('Kira N.', 'Survey', 'high', 'support', 'revenue', 'negative', 'Live chat is unavailable during our core business hours.'),
  ('Darren F.', 'Chat', 'medium', 'security', 'efficiency', 'neutral', 'Would like role-based alerts for security events.'),
  ('Hana Q.', 'In-app', 'low', 'product', 'retention', 'positive', 'The template library keeps my team aligned on messaging.'),
  ('Gus V.', 'Email', 'high', 'performance', 'revenue', 'negative', 'Real-time metrics lag behind by 10 minutes during launches.'),
  ('Mia C.', 'Survey', 'medium', 'ux', 'adoption', 'neutral', 'Tutorial videos are good, but in-product tips need refresh.'),
  ('Ravi B.', 'In-app', 'low', 'support', 'efficiency', 'positive', 'The new knowledge base solved most of our questions.'),
  ('Serena Y.', 'Chat', 'high', 'security', 'retention', 'negative', 'Need automated data retention policies before contract renewal.'),
  ('Tariq Z.', 'Email', 'medium', 'pricing', 'revenue', 'neutral', 'Usage-based overages should be clearer on invoices.');
